### ISSUE TITLE
Bug: Non-dev bundle fails due to handling of Params

### ISSUE THREAD

**Issue by rdohms** [fnando/streamdeck#50]
## Description

Trying to run a bundle command without the `--dev` flag fails, due to the now `undefined` value of `params.dev`

## How to reproduce

run `bundle`

## What do you expect

For bundle to work the same way as `bundle --dev`

## What happened instead

The build fails due to the `__DEV__` variable.

> node_modules/esbuild/lib/main.js:299:10: ERROR: Expected value for define "__DEV__" to be a string, got undefined instead

## Software:

- version: sdplus-support branch

## Full backtrace

```text
/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:299:10: ERROR: Expected value for define "__DEV__" to be a string, got undefined instead
    at failureErrorWithLog (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:953:16
    at responseCallbacks.<computed> (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      id: '',
      pluginName: '',
      text: 'Expected value for define "__DEV__" to be a string, got undefined instead',
      location: [Object],
      notes: [],
      detail: Error: Expected value for define "__DEV__" to be a string, got undefined instead
          at validateStringValue (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:299:11)
          at pushCommonFlags (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:390:37)
          at flagsForBuildOptions (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:424:3)
          at buildOrContextContinue (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:1009:9)
          at buildOrContextImpl (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:993:5)
          at Object.buildOrContext (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:776:5)
          at /Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:2163:15
          at new Promise (<anonymous>)
          at Object.build (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:2162:25)
          at build (/Users/rdohms/dev/elgato/com.dms.streamdeck.github-prs/node_modules/esbuild/lib/main.js:2011:51)
    }
  ],
  warnings: []
}

```

**Comment by rdohms** [comment]
Workaround that I found was to adjust this [line](https://github.com/fnando/streamdeck/blob/main/src/cli/bundle.ts#L196) and this [line](https://github.com/fnando/streamdeck/blob/main/src/cli/bundle.ts#L225) to be:

```
    define: {
      __DEV__: JSON.stringify(params.dev ?? true),
    },
```

This is because the default value is to be undefined, and something under the hood does not like that.
